services:
  whisper-live:
    image: ghcr.io/collabora/whisperlive-gpu:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  local-ai:
    image: localai/localai:v2.24.0-cublas-cuda12
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
